### ISSUE TITLE
panic: protobuf tag not enough fields in PathExistsResponse.state

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-proxy#159]
**What happened**:
related smb code: https://github.com/kubernetes-csi/csi-driver-smb/blob/8ec0d721cf63e93a324689c17868fd433d193afd/pkg/mounter/safe_mounter_windows.go#L221-L224

```console
PS C:\Users\xiazhang\Downloads\csi-proxy-v1.0.0-rc.1.tar\bin> .\csi-proxy.exe --kubelet-path C:\Users\xiazhang\go\src\github.com\kubernetes-csi\csi-driver-smb\pkg\smb\ --v 10
I0705 09:29:22.634987   26268 main.go:54] Starting CSI-Proxy Server ...
I0705 09:29:22.636127   26268 main.go:55] Version: v1.0.0-rc.1-0-g327ebfb
I0705 09:29:31.082178   26268 server.go:105] Request: PathExists with path="C:\\Users\\xiazhang\\go\\src\\github.com\\kubernetes-csi\\csi-driver-smb\\pkg\\smb\\test-csi"
```

```
C:\Users\xiazhang\go\src\github.com\kubernetes-csi\csi-driver-smb\pkg\smb>go test -run TestCreateVolume
panic: protobuf tag not enough fields in PathExistsResponse.state:  [recovered]
        panic: protobuf tag not enough fields in PathExistsResponse.state:

goroutine 14 [running]:
testing.tRunner.func1(0xc00022c600)
        c:/go/src/testing/testing.go:874 +0x3aa
panic(0x155dcc0, 0xc0004170b0)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/golang/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc0003c0140)
        C:/Users/xiazhang/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/table_unmarshal.go:332 +0x16aa
github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0003c0140, 0xc000332090, 0xc000366088, 0x2, 0x2, 0x40d6bf, 0x20)
        C:/Users/xiazhang/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/table_unmarshal.go:136 +0xde7
github.com/golang/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc000364120, 0x4a14130, 0xc000332090, 0xc000366088, 0x2, 0x2, 0x3, 0x0)
        C:/Users/xiazhang/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/table_unmarshal.go:63 +0x6d
github.com/golang/protobuf/proto.(*Buffer).Unmarshal(0xc000368458, 0x4a14130, 0xc000332090, 0x0, 0x0)
        C:/Users/xiazhang/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/decode.go:424 +0x1f3
google.golang.org/grpc/encoding/proto.codec.Unmarshal(0xc000366088, 0x2, 0x2, 0x16acb80, 0xc000332090, 0xc00034f040, 0x5159a3)
        C:/Users/xiazhang/go/pkg/mod/google.golang.org/grpc@v1.27.0/encoding/proto/proto.go:93 +0x135
google.golang.org/grpc.recv(0xc0002ef000, 0x28ec538, 0x26670b0, 0xc00022c700, 0x0, 0x0, 0x16acb80, 0xc000332090, 0x400000, 0x0, ...)
        C:/Users/xiazhang/go/pkg/mod/google.golang.org/grpc@v1.27.0/rpc_util.go:711 +0x116
google.golang.org/grpc.(*csAttempt).recvMsg(0xc0002e0980, 0x16acb80, 0xc000332090, 0x0, 0xc000043e00, 0x54)
        C:/Users/xiazhang/go/pkg/mod/google.golang.org/grpc@v1.27.0/stream.go:885 +0xf4
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc0002e0980, 0x54, 0x54)
        C:/Users/xiazhang/go/pkg/mod/google.golang.org/grpc@v1.27.0/stream.go:736 +0x4d
google.golang.org/grpc.(*clientStream).withRetry(0xc0002d9320, 0xc00034f310, 0xc00034f2e0, 0xc000043e00, 0xc000185e00)
        C:/Users/xiazhang/go/pkg/mod/google.golang.org/grpc@v1.27.0/stream.go:594 +0xa3
google.golang.org/grpc.(*clientStream).RecvMsg(0xc0002d9320, 0x16acb80, 0xc000332090, 0x0, 0x0)
        C:/Users/xiazhang/go/pkg/mod/google.golang.org/grpc@v1.27.0/stream.go:735 +0x10a
google.golang.org/grpc.invoke(0x1a4e740, 0xc00003a0e8, 0x183aedc, 0x19, 0x16acac0, 0xc000304480, 0x16acb80, 0xc000332090, 0xc000222a80, 0x0, ...)
        C:/Users/xiazhang/go/pkg/mod/google.golang.org/grpc@v1.27.0/call.go:73 +0x142
google.golang.org/grpc.(*ClientConn).Invoke(0xc000222a80, 0x1a4e740, 0xc00003a0e8, 0x183aedc, 0x19, 0x16acac0, 0xc000304480, 0x16acb80, 0xc000332090, 0x0, ...)
        C:/Users/xiazhang/go/pkg/mod/google.golang.org/grpc@v1.27.0/call.go:37 +0x1ba
github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1.(*filesystemClient).PathExists(0xc0002f5d20, 0x1a4e740, 0xc00003a0e8, 0xc000304480, 0x0, 0x0, 0x0, 0x8898ea, 0x2646980, 0x1c0008)
        C:/Users/xiazhang/go/pkg/mod/github.com/kubernetes-csi/csi-proxy/client@v1.0.0-rc.1/api/filesystem/v1/api.pb.go:840 +0xdb
github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1.(*Client).PathExists(...)
        C:/Users/xiazhang/go/pkg/mod/github.com/kubernetes-csi/csi-proxy/client@v1.0.0-rc.1/groups/filesystem/v1/client_generated.go:81
github.com/kubernetes-csi/csi-driver-smb/pkg/mounter.(*CSIProxyMounter).ExistsPath(0xc0002f5e20, 0xc000043b60, 0x52, 0x0, 0x0, 0x0)
        C:/Users/xiazhang/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/mounter/safe_mounter_windows.go:221 +0x198
github.com/kubernetes-csi/csi-driver-smb/pkg/mounter.(*CSIProxyMounter).IsLikelyNotMountPoint(0xc0002f5e20, 0xc000043b60, 0x52, 0xc00028fa40, 0x50, 0x50)
        C:/Users/xiazhang/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/mounter/safe_mounter_windows.go:164 +0xff
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).ensureMountPoint(0xc0002c0c80, 0xc000043b60, 0x52, 0xc0002eeea0, 0x0, 0x0)
        C:/Users/xiazhang/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/nodeserver.go:325 +0x6d
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).NodeStageVolume(0xc0002c0c80, 0x1a4e740, 0xc00003a100, 0xc000327bf8, 0x0, 0x0, 0x0)
        C:/Users/xiazhang/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/nodeserver.go:183 +0x7b9
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).internalMount(0xc0002c0c80, 0x1a4e740, 0xc00003a100, 0xc000304440, 0xc000304380, 0xc0002d1f20, 0x0, 0x0)
        C:/Users/xiazhang/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/controllerserver.go:243 +0x319
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).CreateVolume(0xc0002c0c80, 0x1a4e740, 0xc00003a100, 0xc0002f72d0, 0x0, 0x0, 0x0)
        C:/Users/xiazhang/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/controllerserver.go:95 +0x321
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.TestCreateVolume.func1(0xc00022c600)
        C:/Users/xiazhang/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/controllerserver_test.go:165 +0x110
testing.tRunner(0xc00022c600, 0xc00028f9f0)
        c:/go/src/testing/testing.go:909 +0xd0
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x357
exit status 2
FAIL    github.com/kubernetes-csi/csi-driver-smb/pkg/smb        0.327s
```

@mauriciopoppe 
cc @jingxu97 

**What you expected to happen**:

**How to reproduce it**:
 - run csi-proxy on Windows node
> download https://github.com/andyzhangx/demo/raw/master/windows/csi-proxy-v1.0.0-rc.1.tar.gz
```console
.\csi-proxy.exe --kubelet-path C:\Users\xiazhang\go\src\github.com\kubernetes-csi\csi-driver-smb\pkg\smb\ --v 10
```

 - run `TestCreateVolume` which invokes csi-proxy `PathExists`
```console
git clone https://github.com/kubernetes-csi/csi-driver-smb.git
cd csi-driver-smb
git fetch origin pull/319/head:319
git checkout 319
cd pkg\smb
C:\Users\xiazhang\go\src\github.com\kubernetes-csi\csi-driver-smb\pkg\smb>go test -run TestCreateVolume
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v1.0.0-rc.1
- Kubernetes version (use `kubectl version`): n/a 
- OS (e.g. from /etc/os-release): Windows 10
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mauriciopoppe** [comment]
Thanks for the info, I was able to reproduce it by following your steps @andyzhangx, from the error it looks like the unmarshalling of the PathExists response is failing, some things I've tried:

- Made sure that the request works in the csi-proxy integration tests https://github.com/kubernetes-csi/csi-proxy/compare/master...mauriciopoppe:smb-test?expand=1
- Made sure that GCE PD CSI driver is not crashing with the same request https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/738
- Recreated the vendor folder for smb-driver my VM, the test still fails
- Tried running csi-proxy with `--kubelet-path C:\`, the test still fails
- Tried matching the go mod versions for protobuf and grpc in smb-driver to be the same as what GCE PD CSI driver is using, the test still fails
- Added more logs to that request, I confirmed that the server is returning the expected response to the client which 

Some other things that I'll try:
- Check that the contents of the libraries in the stack call are exactly the same between GCE PD CSI driver and SMB driver
- Add an interceptor to read unparsed data in both driver

The logs that I have at the moment:

```
# server
I0705 06:52:13.076230    7392 server.go:105] Request: PathExists with path="C:\\Users\\mauriciopoppe\\go\\src\\github.com\\kubernetes-csi\\csi-driver-smb\\pkg\\smb\\test-csi"
I0705 06:52:13.076298    7392 server.go:120] validation layer response=&{true}
I0705 06:52:13.089885    7392 server_generated.go:104] versioned response=exists:true
```

```
# client

PS C:\Users\mauriciopoppe\go\src\github.com\kubernetes-csi\csi-driver-smb\pkg\smb> go test -run TestCreateVolume
--- FAIL: TestCreateVolume (0.03s)
    --- FAIL: TestCreateVolume/valid_defaults (0.03s)
panic: protobuf tag not enough fields in PathExistsResponse.state:  [recovered]
        panic: protobuf tag not enough fields in PathExistsResponse.state:

goroutine 26 [running]:
testing.tRunner.func1.2(0x23c1a00, 0xc00036e010)
        C:/Program Files/Go/src/testing/testing.go:1143 +0x345
testing.tRunner.func1(0xc000336600)
        C:/Program Files/Go/src/testing/testing.go:1146 +0x4b6
panic(0x23c1a00, 0xc00036e010)
        C:/Program Files/Go/src/runtime/panic.go:965 +0x1c7
github.com/golang/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc0002ecaa0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/github.com/golang/protobuf/proto/table_unmarshal.go:332 +0x1777
github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0002ecaa0, 0xc000346030, 0xc0001b3ca8, 0x2, 0x2, 0x139f2ff, 0x20)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/github.com/golang/protobuf/proto/table_unmarshal.go:136 +0xf65
github.com/golang/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc0002e9b80, 0x18bbbce6a18, 0xc000346030, 0xc0001b3ca8, 0x2, 0x2, 0x1, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/github.com/golang/protobuf/proto/table_unmarshal.go:63 +0x6d
github.com/golang/protobuf/proto.(*Buffer).Unmarshal(0xc0003462d8, 0x18bbbce6a18, 0xc000346030, 0x0, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/github.com/golang/protobuf/proto/decode.go:424 +0x1f5
google.golang.org/grpc/encoding/proto.codec.Unmarshal(0xc0001b3ca8, 0x2, 0x2, 0x24706a0, 0xc000346030, 0x2, 0x2)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/google.golang.org/grpc/encoding/proto/proto.go:93 +0x13d
google.golang.org/grpc.recv(0xc000004120, 0x18bbbce2148, 0x30db2e0, 0xc000396100, 0x0, 0x0, 0x24706a0, 0xc000346030, 0x400000, 0x0, ...)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/google.golang.org/grpc/rpc_util.go:711 +0x11c
google.golang.org/grpc.(*csAttempt).recvMsg(0xc0002fc980, 0x24706a0, 0xc000346030, 0x0, 0x0, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/google.golang.org/grpc/stream.go:885 +0xf4
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc0002fc980, 0xc0000448a0, 0x59)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/google.golang.org/grpc/stream.go:736 +0x4d
google.golang.org/grpc.(*clientStream).withRetry(0xc0002f4fc0, 0xc00008b2e8, 0xc00008b2b8, 0xc00003c0c8, 0xc000346060)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/google.golang.org/grpc/stream.go:594 +0xa6
google.golang.org/grpc.(*clientStream).RecvMsg(0xc0002f4fc0, 0x24706a0, 0xc000346030, 0x0, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/google.golang.org/grpc/stream.go:735 +0x10d
google.golang.org/grpc.invoke(0x27860b0, 0xc00009a0b0, 0x25ba1d8, 0x19, 0x24705e0, 0xc0003382c0, 0x24706a0, 0xc000346030, 0xc0001c1880, 0x0, ...)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/google.golang.org/grpc/call.go:73 +0x14f
google.golang.org/grpc.(*ClientConn).Invoke(0xc0001c1880, 0x27860b0, 0xc00009a0b0, 0x25ba1d8, 0x19, 0x24705e0, 0xc0003382c0, 0x24706a0, 0xc000346030, 0x0, ...)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/google.golang.org/grpc/call.go:37 +0x1c5
github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1.(*filesystemClient).PathExists(0xc00030fd40, 0x27860b0, 0xc00009a0b0, 0xc0003382c0, 0x0, 0x0, 0x0, 0x23c92e0, 0x0, 0xc000341590)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/github.com/kubernetes-csi/csi-proxy/client/api/filesystem/v1/api.pb.go:840 +0xdb
github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1.(*Client).PathExists(...)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/vendor/github.com/kubernetes-csi/csi-proxy/client/groups/filesystem/v1/client_generated.go:81
github.com/kubernetes-csi/csi-driver-smb/pkg/mounter.(*CSIProxyMounter).ExistsPath(0xc00030fe40, 0xc000083c80, 0x57, 0x0, 0x0, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/mounter/safe_mounter_windows.go:221 +0x1c2
github.com/kubernetes-csi/csi-driver-smb/pkg/mounter.(*CSIProxyMounter).IsLikelyNotMountPoint(0xc00030fe40, 0xc000083c80, 0x57, 0x100000000000000, 0x18bbbb31988, 0x1412ee9)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/mounter/safe_mounter_windows.go:164 +0x131
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).ensureMountPoint(0xc0002ec960, 0xc000083c80, 0x57, 0xc0002a1e78, 0x0, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/nodeserver.go:325 +0x6d
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).NodeStageVolume(0xc0002ec960, 0x27860b0, 0xc00009a0b8, 0xc000341c30, 0x0, 0x0, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/nodeserver.go:183 +0x811
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).internalMount(0xc0002ec960, 0x27860b0, 0xc00009a0b8, 0xc000338280, 0xc0003381c0, 0xc0002ebec0, 0x0, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/controllerserver.go:243 +0x334
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.(*Driver).CreateVolume(0xc0002ec960, 0x27860b0, 0xc00009a0b8, 0xc0003131f0, 0x0, 0x0, 0x0)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/controllerserver.go:95 +0x35f
github.com/kubernetes-csi/csi-driver-smb/pkg/smb.TestCreateVolume.func1(0xc000336600)
        C:/Users/mauriciopoppe/go/src/github.com/kubernetes-csi/csi-driver-smb/pkg/smb/controllerserver_test.go:165 +0x112
testing.tRunner(0xc000336600, 0xc0002a99f0)
        C:/Program Files/Go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1238 +0x2b3
exit status 2
FAIL    github.com/kubernetes-csi/csi-driver-smb/pkg/smb        0.747s
```

**Comment by mauriciopoppe** [comment]
I found out that the protobuf version in SMB driver is somehow not able to unmarshall the response, @andyzhangx please upgrade the github.com/golang/protobuf version to v1.4.3

I see in the server logs that the `PathExists` request went through without a panic, I didn't set any smb env vars so I think that's why the test didn't finish but that should be ok in your unit tests.

```
I0706 20:35:02.406602    7392 server.go:105] Request: PathExists with path="C:\\Users\\mauriciopoppe\\go\\src\\github.com\\kubernetes-csi\\csi-driver-smb\\pkg\\smb"
I0706 20:35:02.406602    7392 server.go:120] validation layer response=&{true}
I0706 20:35:02.407622    7392 server_generated.go:104] versioned response=exists:true
I0706 20:35:02.408705    7392 server.go:36] calling NewSmbGlobalMapping with remote path "test-server\\baseDir"
I0706 20:35:04.739651    7392 server.go:69] Remote test-server\baseDir not mapped. Mapping now!
E0706 20:35:06.266520    7392 server.go:72] failed NewSmbGlobalMapping NewSmbGlobalMapping failed. output: "New-SmbGlobalMapping : The parameter is incorrect. \r\nAt line:1 char:190\r\n+ ... ser, $PWord;New-SmbGlobalMapping -RemotePath $Env:smbremotepath -Cred ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidArgument: (MSFT_SmbGlobalMapping:ROOT/Microsoft/...mbGlobalMapping) [New-SmbGloba \r\n   lMapping], CimException\r\n    + FullyQualifiedErrorId : Windows System Error 87,New-SmbGlobalMapping\r\n \r\n", err: exit status 1
```

Client test logs:
```
PS C:\Users\mauriciopoppe\go\src\github.com\kubernetes-csi\csi-driver-smb\pkg\smb> go test -run TestCreateVolume
Skipping checks on Windows ENV
PASS
ok      github.com/kubernetes-csi/csi-driver-smb/pkg/smb        4.499s
```

**Comment by ddebroy** [comment]
Maybe some variation of https://github.com/gogo/protobuf/issues/678?

**Comment by andyzhangx** [comment]
thanks for the help! issue resolved after migrating to github.com/golang/protobuf v1.4.3 version
