### ISSUE TITLE
Does not start - exits with panic

### ISSUE THREAD

**Issue by philipp1992** [kubernetes-csi/csi-proxy#199]
Hi,

we have compiled the csiproxy with go 1.17.6 and started it according to the instructions as a windows service.

Unfortunately it does not seem to run.
When we start it manually, it exists with a panic.

```
[Administrator@CHMUW-xxx-W]: C:\etc\kubernetes\logs> cat .\csi-proxy.log
Log file created at: 2022/02/16 12:14:11
Running on machine: chmuw-default-windows-zvvxd
Binary: Built with gc go1.15.14 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0216 12:14:11.704148    9872 main.go:142] Running as a Windows service.
I0216 12:14:11.721020    9872 main.go:64] Starting CSI-Proxy Server ...
I0216 12:14:11.721020    9872 main.go:65] Version: v1.0.2-36-g556e1ea
I0216 12:14:11.704660    9872 main.go:152] Windows Service initialized through SCM
I0216 12:14:11.721020    9872 main.go:84] Working directories: %v[C:\var\lib\kubelet]
Log file created at: 2022/02/16 12:29:38
Running on machine: chmuw-default-windowsxxx
Binary: Built with gc go1.17.6 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0216 12:29:38.452284   12060 main.go:142] Running as a Windows service.
I0216 12:29:38.452828   12060 main.go:152] Windows Service initialized through SCM
I0216 12:29:38.472060   12060 main.go:64] Starting CSI-Proxy Server ...
I0216 12:29:38.472060   12060 main.go:65] Version: v1.0.2-36-g556e1ea
I0216 12:29:38.472060   12060 main.go:84] Working directories: %v[C:\var\lib\kubelet]
Log file created at: 2022/02/16 12:32:32
Running on machine: chmuw-default-windows-xxx
Binary: Built with gc go1.17.6 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0216 12:32:32.055607    2064 main.go:142] Running as a Windows service.
I0216 12:32:32.055607    2064 main.go:152] Windows Service initialized through SCM
I0216 12:32:32.083475    2064 main.go:64] Starting CSI-Proxy Server ...
I0216 12:32:32.083475    2064 main.go:65] Version: v1.0.2-36-g556e1ea
I0216 12:32:32.084022    2064 main.go:84] Working directories: %v[C:\var\lib\kubelet]
```
```

[Administrator@CHMUW-DEFAULT-W]: C:\etc\kubernetes\node\bin> .\csi-proxy.exe --working-dir=c:\var\lib\kubelet
I0216 12:40:43.836545    2948 main.go:64] Starting CSI-Proxy Server ...
I0216 12:40:43.862021    2948 main.go:65] Version: v1.0.2-36-g556e1ea
I0216 12:40:43.862021    2948 main.go:84] Working directories: %v[c:\var\lib\kubelet C:\var\lib\kubelet]
panic: ([]error) 0xc000004c48

goroutine 1 [running]:
main.main()
        /root/csi-proxy/cmd/csi-proxy/main.go:73 +0x1fd

```
```

OS Name:                   Microsoft Windows Server Standard
OS Version:                10.0.19041 N/A Build 19041
```

**Comment by philipp1992** [comment]
worked as intented. panics when you try to run it twice.
